version: "3.8"

services:
  api:
    build: .
    ports:
      - 8001:8080
    networks:
      - leonardo-private-1

networks:
  leonardo-private-1:
    name: mariadb_leonardo-private-1
    external: true
