version: "3"

services:
  hoolibo-api:
    build: .
    ports:
      - 8080:8080
    networks:
      - hoolibo-private-1

networks:
  hoolibo-private-1:
    name: mariadb_hoolibo-private-1
    external: true
