services:
  api:
    build: .
    restart: unless-stopped

    depends_on:
      - mariadb
      - redis
    
    environment:
      REDIS_HOST: redis
      DATABASE_HOST: jdbc:mariadb://mariadb:3306/trops
      DATABASE_USER: root
      DATABASE_PASSWORD: ${TROPS_DB_PASSWORD}
    
    ports:
      - 8080:8080
    
    networks:
      - trops-backend-net

  mariadb:
    image: mariadb
    restart: unless-stopped
    
    environment:
      MARIADB_ROOT_PASSWORD: ${TROPS_DB_PASSWORD}

    volumes:
      - ./mariadb:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/1.sql
    
    networks:
      - trops-backend-net
    
  redis:
    image: redis:alpine
    restart: unless-stopped

    volumes:
      - ./redis:/data
    
    networks:
      - trops-backend-net

networks:
  trops-backend-net:
    driver: bridge
