version: "3.8"

services:
  redis:
    image: redis
    restart: always
    networks:
      - backend
  db:
    image: mariadb
    restart: always
    environment:
      - MARIADB_ROOT_PASSWORD=${TROPS_DB_PASSWORD}
    networks:
      - backend
    volumes:
      - "./target/mariadb:/var/lib/mysql"
      - "./init.sql:/docker-entrypoint-initdb.d/1.sql"
  api:
    build: .
    restart: always
    environment:
      - DATABASE_HOST=jdbc:mariadb://db:3306/trops
      - DATABASE_USER=${TROPS_DB_USER}
      - DATABASE_PASSWORD=${TROPS_DB_PASSWORD}
    ports:
      - 8001:8080
    depends_on:
      - redis
      - db
    networks:
      - backend

networks:
  backend:
    name: Trops backend network
    driver: bridge
