version: "3.8"

services:
  redis:
    image: redis
    restart: always
    networks:
      - backend
  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: athena
    networks:
      - backend
  api:
    build: .
    restart: always
    environment:
      - DATABASE_HOST=jdbc:mariadb://db:3306/hoolibo
      - DATABASE_USER=${HOOLIBO_DB_USER}
      - DATABASE_PASSWORD=${HOOLIBO_DB_PASSWORD}
    ports:
      - 8001:8080
    networks:
      - backend

networks:
  backend:
    name: Hoolibo backend network
    driver: bridge
